### ISSUE TITLE
Not sending mail

### ISSUE THREAD

**Issue by tedeu** [AfterShip/apps-opencart#5]
Hi.
It's almost working.
I have opencart 2.1.0.1 
And when I go to orders, and update the order, it works, but when i tick "Nitofy Customer" nad has to send a mail then it doesn't work.
I get this error in the log:
2016-06-23 11:55:17 - PHP Notice: Error: RCPT TO not accepted from server! in /public_html/system/library/mail.php on line 346

Please help me.
Thank you.

**Comment by debopamsengupta** [comment]
Hi, it could be caused by incorrect mail server configurations. We found similar mail problem in the forum thread here, about sending email from a contact form: 

http://forum.opencart.com/viewtopic.php?f=20&t=39703

**Comment by nodrogs** [comment]
Hi, I to am having email issues after installing Aftership on version 2.1.0.1.  The issue is that it does not notify me when a new order is placed.  The customer still receives the email ok.  Setting aftership status to disabled in modules lets me get new notifications again (obviously then I can't use aftership!).
